import GraybillDeal.UniversalEqualMomentBridge

#print axioms GraybillDeal.universalEqualQuotientIdentities_of_centered_identity
#print axioms GraybillDeal.UniversalPosteriorIdentity.equal_quotientIdentities
