import GraybillDeal.UniversalInteriorDecision

#check GraybillDeal.PositiveFinitePrior
#check GraybillDeal.PositiveFinitePrior.bayesAction
#check GraybillDeal.HasPositiveFiniteBayesApproximation
#check GraybillDeal.PositiveFiniteBayesCompleteClassProperty
#check GraybillDeal.hasPositiveFiniteBayesApproximation_of_admissible
#check GraybillDeal.UniversalInteriorFiniteBayesCompleteClassProperty
#check GraybillDeal.HasUniversalInteriorFiniteBayesApproximation
#check GraybillDeal.PositiveFinitePrior.toUniversalInteriorFinitePrior
#check GraybillDeal.universalInteriorExtendedLikelihood
#check GraybillDeal.universalInteriorExtendedLikelihood_eq_reducedLikelihood
#check GraybillDeal.PositiveFinitePrior.bayesAction_extendedLikelihood_eq_fullReduced
#check GraybillDeal.exists_universalPosteriorIdentity_of_ae_openFinitePrior_tendsto

#print axioms GraybillDeal.PositiveFinitePrior.bayesAction_extendedLikelihood_eq_fullReduced
#print axioms GraybillDeal.exists_universalPosteriorIdentity_of_ae_openFinitePrior_tendsto
