import GraybillDeal.UniversalCompleteClassExhaustion

#print axioms GraybillDeal.CompleteClass.FiniteMeasureExhaustion.spanningSets
#print axioms GraybillDeal.CompleteClass.ae_tendsto_of_exhausting_badSets_summable
#print axioms GraybillDeal.CompleteClass.ae_tendsto_of_exhausting_geometric_badSet_bound
#print axioms GraybillDeal.CompleteClass.hasPositiveFiniteBayesApproximation_of_compatibleLocal
#print axioms GraybillDeal.CompleteClass.hasPositiveFiniteBayesApproximation_of_sigmaFinite_compatibleLocal
#print axioms
  GraybillDeal.CompleteClass.measurablePositiveFiniteBayesCompleteClassProperty_of_compatibleLocal
