import GraybillDeal.UnequalDampedAlgebra
#check div_le_div_iff₀
#check div_le_div_iff_of_pos_right
#check sq_le_sq₀
#check sq_le_sq
#check sq_abs
#check abs_sq
#check mul_le_mul
#check one_div
#check inv_le_inv₀
#check div_sub_div
#check div_sub_div_same
#check div_eq_iff
#check eq_div_iff
