import GraybillDeal.UnequalFixedDifferenceFourRawRisk
import GraybillDeal.UnequalFixedDifferenceFourRealAlgebra
import GraybillDeal.UnequalFixedDifferenceFourAllNAlgebra
import GraybillDeal.UnequalFixedDifferenceFourRealMoments
import GraybillDeal.UnequalFixedDifferenceFourRealSeriesSign
import GraybillDeal.UnequalFixedDifferenceFourRealReduced
import GraybillDeal.UnequalFixedDifferenceFourRealCanonicalReduced
import GraybillDeal.UnequalFixedDifferenceFourRealCanonicalSummary
import GraybillDeal.UnequalFixedDifferenceFourAllNRawRisk

/-!
# Axiom audit for the fixed-difference-four family checkpoint

This file prints the axioms of the central algebraic and series-sign
theorems.  It is intentionally separate from the main import tree.
-/

#print axioms GraybillDeal.unequalFixedDifferenceFourKappa_lt_one
#print axioms GraybillDeal.unequalFixedDifferenceFourB0_pos
#print axioms GraybillDeal.unequalFixedDifferenceFourMMinus_lt_MPlus
#print axioms GraybillDeal.unequalFixedDifferenceFour_reducedRisk_neg_of_bounds
#print axioms GraybillDeal.unequalFD4TailPlus_pos
#print axioms GraybillDeal.unequalFD4TailMinus_pos
#print axioms GraybillDeal.unequalFixedDifferenceFourPlusCoeff_neg
#print axioms GraybillDeal.unequalFixedDifferenceFourMinusCoeff_neg
#print axioms GraybillDeal.unequalFixedDifferenceFourPlusSeries_le_neg_b0
#print axioms GraybillDeal.unequalFixedDifferenceFourMinusSeries_le_neg_b0
#print axioms GraybillDeal.integral_rpow_mul_one_sub_rpow_betaMeasure_eq_beta_ratio
#print axioms GraybillDeal.integral_pow_betaMeasure_unequalFixedDifferenceFourPlus
#print axioms GraybillDeal.integral_pow_betaMeasure_unequalFixedDifferenceFourMinus
#print axioms GraybillDeal.unequalFixedDifferenceFourPlusIntegratedCoefficient_eq_coeff
#print axioms GraybillDeal.unequalFixedDifferenceFourMinusIntegratedCoefficient_eq_coeff
#print axioms GraybillDeal.integral_unequalFixedDifferenceFourPlusC_le
#print axioms GraybillDeal.integral_unequalFixedDifferenceFourMinusC_le
#print axioms GraybillDeal.unequalFixedDifferenceFourPlusAnalyticH_le_neg_b0
#print axioms GraybillDeal.unequalFixedDifferenceFourMinusAnalyticH_le_neg_b0
#print axioms GraybillDeal.unequalFixedDifferenceFourPlusReducedRisk_neg
#print axioms GraybillDeal.unequalFixedDifferenceFourMinusReducedRisk_neg
#print axioms GraybillDeal.unequalFixedDifferenceFourCanonicalReducedRisk_neg
#print axioms GraybillDeal.unequalFixedDifferenceFourCanonicalMomentBridge_of_component_laws
#print axioms GraybillDeal.unequalFixedDifferenceFourCanonicalClippedEstimatorRiskDifference_neg_of_summary_laws
#print axioms GraybillDeal.unequalFixedDifferenceFourRawNormalSummaryLaws_of_normal_samples
#print axioms GraybillDeal.unequalFixedDifferenceFourCanonicalClippedEstimatorRiskDifference_neg_of_raw_normal
#print axioms GraybillDeal.unequalFixedDifferenceFourRawClippedPerturbedEstimator_sqRisk_lt_rawGraybillDealEstimator
#print axioms GraybillDeal.unequalFixedDifferenceFourRealKappa_lt_one
#print axioms GraybillDeal.unequalFixedDifferenceFourRealMMinus_lt_MPlus
#print axioms GraybillDeal.unequalFixedDifferenceFourReal_reducedRisk_neg_of_bounds
#print axioms GraybillDeal.integral_pow_betaMeasure_unequalFixedDifferenceFourRealPlus
#print axioms GraybillDeal.integral_pow_betaMeasure_unequalFixedDifferenceFourRealMinus
#print axioms GraybillDeal.integral_unequalFixedDifferenceFourRealPlusDensity_pow
#print axioms GraybillDeal.integral_unequalFixedDifferenceFourRealMinusDensity_pow
#print axioms GraybillDeal.unequalFixedDifferenceFourRealPlusCoeff_neg
#print axioms GraybillDeal.unequalFixedDifferenceFourRealMinusCoeff_neg
#print axioms GraybillDeal.unequalFixedDifferenceFourRealPlusSeries_le_neg_b0
#print axioms GraybillDeal.unequalFixedDifferenceFourRealMinusSeries_le_neg_b0
#print axioms GraybillDeal.unequalFixedDifferenceFourAllN_reducedRisk_neg_of_bounds
#print axioms GraybillDeal.unequalFixedDifferenceFourSampleEpsilon_fourteen
#print axioms GraybillDeal.unequalFixedDifferenceFourRealC_pointwise_le_envelope
#print axioms GraybillDeal.unequalFixedDifferenceFourRealPlusIntegratedCoefficient_eq_polynomial
#print axioms GraybillDeal.unequalFixedDifferenceFourRealMinusIntegratedCoefficient_eq_polynomial
#print axioms GraybillDeal.unequalFixedDifferenceFourRealPlusPolynomialCoefficient_eq_coeff
#print axioms GraybillDeal.unequalFixedDifferenceFourRealMinusPolynomialCoefficient_eq_coeff
#print axioms GraybillDeal.unequalFixedDifferenceFourRealPlusIntegratedCoefficient_eq_coeff
#print axioms GraybillDeal.unequalFixedDifferenceFourRealMinusIntegratedCoefficient_eq_coeff
#print axioms GraybillDeal.unequalFixedDifferenceFourRealPlusAnalyticH_le_neg_b0
#print axioms GraybillDeal.unequalFixedDifferenceFourRealMinusAnalyticH_le_neg_b0
#print axioms GraybillDeal.integral_unequalFixedDifferenceFourRealEnvelopeFactor_plus
#print axioms GraybillDeal.integral_unequalFixedDifferenceFourRealEnvelopeFactor_minus
#print axioms GraybillDeal.unequalFixedDifferenceFourRealPlusReducedRisk_neg
#print axioms GraybillDeal.unequalFixedDifferenceFourRealMinusReducedRisk_neg
#print axioms GraybillDeal.unequalFixedDifferenceFourRealCanonicalDenom_pos
#print axioms GraybillDeal.integral_betaMeasure_unequalFixedDifferenceFourReal_complement
#print axioms GraybillDeal.unequalFixedDifferenceFourRealCanonicalB_eq_plus
#print axioms GraybillDeal.unequalFixedDifferenceFourRealCanonicalC_eq_plus
#print axioms GraybillDeal.unequalFixedDifferenceFourRealCanonicalB_eq_minus
#print axioms GraybillDeal.unequalFixedDifferenceFourRealCanonicalC_eq_minus
#print axioms GraybillDeal.unequalFixedDifferenceFourRealCanonicalReducedRisk_neg
#print axioms GraybillDeal.unequalFixedDifferenceFourRealCanonicalMomentBridge_of_canonical_expectations
#print axioms GraybillDeal.unequalFixedDifferenceFourRealCanonicalMomentBridge_of_component_laws
#print axioms GraybillDeal.unequalFixedDifferenceFourRealCanonicalClippedEstimatorRiskDifference_neg_of_component_laws
#print axioms GraybillDeal.unequalFixedDifferenceFourRealCanonicalClippedEstimatorRiskDifference_neg_of_summary_laws
#print axioms GraybillDeal.unequalFixedDifferenceFourAllNRawNormalSummaryLaws_of_normal_samples
#print axioms GraybillDeal.TwoNormalSamplesU.ae_ne_unequalFixedDifferenceFourAllNNormalRawL
#print axioms GraybillDeal.TwoNormalSamplesU.ae_eq_unequalFixedDifferenceFourAllNCanonicalBaseEstimator_raw
#print axioms GraybillDeal.TwoNormalSamplesU.ae_eq_unequalFixedDifferenceFourAllNCanonicalClippedEstimator_raw
#print axioms GraybillDeal.unequalFixedDifferenceFourAllNCanonicalClippedEstimatorRiskDifference_neg_of_raw_normal
#print axioms GraybillDeal.unequalFixedDifferenceFourAllNRawClippedPerturbedEstimator_sqRisk_lt_rawGraybillDealEstimator
