import GraybillDeal.UniversalCanonicalComponentDensity
import GraybillDeal.UniversalCanonicalReducedTheorem
import GraybillDeal.UniversalClosedConvexLocalTheorem
import GraybillDeal.UniversalCompactAction
import GraybillDeal.UniversalConditionalRawTheorem
import GraybillDeal.UniversalFinitePriorBayesRisk
import GraybillDeal.UniversalFiniteStatisticalCompleteClass
import GraybillDeal.UniversalFiniteStatisticalRiskSet
import GraybillDeal.UniversalGammaPositiveSupport
import GraybillDeal.UniversalHilbertUnconditionalTheorem
import GraybillDeal.UniversalNestedDensityBridge
import GraybillDeal.UniversalRawAdmissibility
import GraybillDeal.UniversalRawComponentLaws
import GraybillDeal.UniversalRawDensityIdentity
import GraybillDeal.UniversalRawLawFamily
import GraybillDeal.UniversalRawLawUnconditional
import GraybillDeal.UniversalRawParameters
import GraybillDeal.UniversalRawRiskTransport
import GraybillDeal.UniversalRawDecisionBridge
import GraybillDeal.UniversalRadialGammaIntegral
import GraybillDeal.UniversalReducedDominator
import GraybillDeal.UniversalReducedChangeOfVariables
import GraybillDeal.UniversalReducedLikelihoodNormalization
import GraybillDeal.UniversalRiskScaling

/-!
Machine-readable axiom audit for the assembled universal theorem stack.
This module is not imported by the library umbrella.
-/

#print axioms GraybillDeal.no_universalPosteriorIdentity
#print axioms GraybillDeal.no_universalPosteriorIdentity_sampleSizes
#print axioms
  GraybillDeal.universalReducedBaseline_not_measurablyAdmissible_of_measurableCompleteClass
#print axioms
  GraybillDeal.canonicalUniversalReducedBaseline_not_measurablyAdmissible_sampleSizes_of_completeClass
#print axioms
  GraybillDeal.canonicalUniversalReducedBaseline_not_measurablyAdmissible_sampleSizes_of_compatibleLocal
#print axioms GraybillDeal.universalRaw_sqRisk_sub_graybillDeal_eq_reduced
#print axioms GraybillDeal.universalRaw_sqRisk_lt_graybillDeal_of_reduced
#print axioms GraybillDeal.universalRawOracleTheta_pos
#print axioms GraybillDeal.universalRawOracleTheta_lt_one
#print axioms
  GraybillDeal.exists_total_canonicalUniversalReduced_dominator_of_completeClass
#print axioms GraybillDeal.DensitySquaredRiskDominates.smul_measure
#print axioms GraybillDeal.universalRaw_sqRisk_le_of_density_domination
#print axioms GraybillDeal.universalRaw_sqRisk_lt_of_density_domination
#print axioms
  GraybillDeal.exists_total_canonicalUniversalReduced_dominator_all_scalings_of_completeClass
#print axioms
  GraybillDeal.exists_total_canonicalUniversalReduced_dominator_all_scalings_of_compatibleLocal
#print axioms GraybillDeal.universalRawOracleTheta_realizing
#print axioms
  GraybillDeal.exists_universalRaw_reducedEstimator_le_of_completeClass_and_laws
#print axioms
  GraybillDeal.exists_strict_scaled_parameter_with_realizing_rawVariances_of_completeClass
#print axioms
  GraybillDeal.lintegral_universalReducedRadialToCanonicalVec
#print axioms
  GraybillDeal.lintegral_universalPreRadialDensity_eq_fullReducedDensity
#print axioms
  GraybillDeal.FiniteStatisticalRiskSet.exists_positiveFinitePrior_supporting_finite_admissible
#print axioms
  GraybillDeal.TwoNormalSamplesU.map_universalRawIndependentComponents_withDensity_sq_meanDifference
#print axioms
  GraybillDeal.exists_universalRaw_dominator_of_completeClass_and_lawFamily
#print axioms
  GraybillDeal.universalRawGraybillDeal_not_admissible_of_completeClass_and_lawFamily
#print axioms
  GraybillDeal.hasUniversalRawReducedLawFamily_of_componentDensityIdentities
#print axioms
  GraybillDeal.universalRawGraybillDeal_not_admissible_of_completeClass_and_componentDensityIdentities
#print axioms
  GraybillDeal.CompleteClass.measurablePositiveFiniteBayesCompleteClassProperty_of_closedConvexLocalRiskSets
#print axioms
  GraybillDeal.canonicalUniversalReducedBaseline_not_measurablyAdmissible_sampleSizes_of_closedConvexLocalRiskSets
#print axioms
  GraybillDeal.FiniteStatisticalRiskSet.exists_positiveFinitePrior_bayesAction_eq_of_finite_admissible
#print axioms
  GraybillDeal.PositiveFinitePrior.finitePriorBayesRisk_decomposition
#print axioms
  GraybillDeal.PositiveFinitePrior.ae_eq_bayesAction_of_finitePriorBayesRisk_eq
#print axioms
  GraybillDeal.map_canonicalWeightedTripleDensity_eq_reducedDensity
#print axioms
  GraybillDeal.map_canonicalWeightedTripleDensity_eq_reducedDensity_of_eqOn
#print axioms
  GraybillDeal.map_universalCanonicalGammaScaling_eq_scaledProductDensity
#print axioms GraybillDeal.gammaMeasure_ae_mem_Ioi_of_pos
#print axioms
  GraybillDeal.universalRiskTiltedComponentReducedDensityIdentity
#print axioms
  GraybillDeal.hasUniversalRawReducedLawFamily_of_twoNormalSampleFamily
#print axioms
  GraybillDeal.exists_universalRaw_dominator_of_completeClass
#print axioms
  GraybillDeal.universalRawGraybillDeal_not_admissible_of_completeClass
#print axioms
  GraybillDeal.PositiveFinitePrior.bayesAction_universalInterior_mem_Icc
#print axioms
  GraybillDeal.ae_mem_Icc_of_measurablyAdmissible_of_normalized
#print axioms
  GraybillDeal.universalReducedLikelihood_lintegral_eq_one
#print axioms
  GraybillDeal.ae_mem_Icc_of_canonicalUniversalReduced_measurablyAdmissible
#print axioms
  GraybillDeal.universalMeasurableFiniteBayesCompleteClassProperty_halfShapes
#print axioms GraybillDeal.exists_universalRaw_dominator
#print axioms GraybillDeal.universalRawGraybillDeal_not_admissible
#print axioms
  GraybillDeal.exists_universalRaw_measurableEstimator_dominator
#print axioms
  GraybillDeal.universalRawGraybillDeal_not_admissible_among_all_measurableEstimators
